# Generated by Django 3.2.7 on 2021-09-07 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_seller_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leftovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.seller')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='leftovers',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.leftovers'),
        ),
    ]
