# Generated by Django 3.2.7 on 2021-09-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20210907_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='leftovers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.leftovers'),
        ),
    ]
