# Generated by Django 3.2.7 on 2021-09-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_delivery_leftovers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='leftovers',
        ),
        migrations.RemoveField(
            model_name='leftovers',
            name='seller',
        ),
        migrations.AddField(
            model_name='leftovers',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='leftovers',
            name='obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.object'),
        ),
        migrations.AlterField(
            model_name='leftovers',
            name='pickup_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='leftovers',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
