# Generated by Django 3.2.7 on 2021-09-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20210907_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
