# Generated by Django 3.2.7 on 2021-09-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20210907_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.AlterModelOptions(
            name='leftovers',
            options={'verbose_name': 'Sobra', 'verbose_name_plural': 'Sobras'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='seller',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
