# Generated by Django 3.2.7 on 2021-09-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20210912_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.TextField(max_length=255, verbose_name='Morada/Localidade'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefone/Telemóvel'),
        ),
    ]
