# Generated by Django 3.2.7 on 2021-09-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20210912_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='leftovers',
            name='pickup_date',
            field=models.DateField(blank=True, verbose_name='Data de Recolha'),
        ),
        migrations.AlterField(
            model_name='leftovers',
            name='quantity',
            field=models.IntegerField(blank=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='object',
            name='seller_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Valor Unitário (vendedor)'),
        ),
        migrations.AlterField(
            model_name='object',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Valor Unitário (venda)'),
        ),
    ]
